### ISSUE TITLE
Cloned process is not killed after dump completes

### ISSUE THREAD

**Issue by roterdam** [mjsabby/CopyOnWriteDump#2]
Finally a working demo of the `PSS` APIs, thank you! This repository should be more popular imho! 

However, there seems to be a bug that after the MiniDump is completed the Suspended Clone process hangs around indefinitely.

I noticed this after I created hundreds of snapshots and looked under Sys Internals Process Explorer.

**Comment by mjsabby** [comment]
This has been fixed.
